name: EC2 auto deploy

on:
  pull_request:
    branches: [main]
    types: [closed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          host=${{ secrets.EC2_URL }}
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
      - name: Deploy
        run: |
          ssh ${{ secrets.EC2_URL }} -i ~/.ssh/id_rsa 'kill `ps ux | grep irclogger.py -m1 | awk "{print \\$2}"`'
          ssh ${{ secrets.EC2_URL }} -i ~/.ssh/id_rsa 'cd maobot-logger-ec2; git pull origin main; pip install -r requirements.txt'
          ssh ${{ secrets.EC2_URL }} -i ~/.ssh/id_rsa 'nohup python3 maobot-logger-ec2/irclogger.py </dev/null >/dev/null 2>&1 &'
