name: EC2 auto deploy

on:
  pull_request:
    branches: [main]
    types: [closed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy
        env:
          EC2_URL: ${{ secrets.EC2_URL }}
        run: |
          ssh $EC2_URL 'kill `ps ux | grep irclogger.py -m1 | awk "{print \\$2}"`'
          ssh $EC2_URL 'cd maobot-logger-ec2; git pull origin main; pip install -r requirements.txt'
          ssh $EC2_URL 'nohup python3 maobot-logger-ec2/irclogger.py </dev/null >/dev/null 2>&1 &'
