name: EC2 auto deploy

on:
  pull_request:
    branches: [main]
    types: [closed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy
        env:
          EC2_URL: ${{ secrets.EC2_URL }}
        run: |
          ssh ubuntu@$EC2_URL 'killall python3; echo "killall exit status: $?"'
          ssh ubuntu@$EC2_URL 'cd maobot-logger-ec2; git pull origin main; pip install -r requirements.txt'
          ssh ubuntu@$EC2_URL 'cp maobot-info.log maobot-info-`date +%Y%m%d%H%M%S`.log'
          ssh ubuntu@$EC2_URL 'cd maobot-logger-ec2; nohup python3 irclogger.py </dev/null >../maobot-info.log 2>&1 &'
